version: '3'
x-spark-common:
  &spark-common
  build: . # from Dockerfile in directory
  entrypoint: ["/bin/bash", "/app/start-cluster.sh"]
  environment:
    &spark-common-env
    SPARK_HOME: /opt/spark

services:
  spark-master:
    <<: *spark-common
    ports:
      - target: 8088  #container
        published: 8088  #host
        protocol: tcp
        mode: host
      - target: 7077
        published: 7077
        protocol: tcp
        mode: host
    environment:
      <<: *spark-common-env
      SPARK_TYPE: master # as the master in cluster
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8088
      PYSPARK_DRIVER_PYTHON: ipython
  spark-worker-1:
    <<: *spark-common
    depends_on:
      - spark-master
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    environment:
      <<: *spark-common-env
      SPARK_MASTER: spark://spark-master:7077 # refers to service "spark-master"
      SPARK_WORKER_WEBUI_PORT: 8081
